### ISSUE TITLE
Support For UNC or SMB Paths

### ISSUE THREAD

**Issue by S-Coding23** [gaseous-project/gaseous-server#535]
I would like to be able to connect a library that is stored either on a Windows device or separate NAS on the local network.

**Comment by michael-j-green** [comment]
Hi @S-Coding23; happy to look into this, but it might be awhile before I get to resolve this.

In the meantime, I would typically address this by mounting the SMB or NFS share on the Linux host (for example at `/games` then adding to the Gaseous docker-compose.yml file under volumes `- /games:/games:ro` (the `:ro` makes it read only), and then adding a Custom Library that points to `/games` (see: https://github.com/gaseous-project/gaseous-server/wiki/Adding-ROMs#custom-library).

Apparently you can also mount SMB as part of the docker-compose.yml file (so the share is scoped to the container), using a structure like:
```yml
volumes: 
  cifs-volume:
    driver_opts:
      type: cifs 
      o: username=youruser,password=yourpassword,uid=1021,gid=100,vers=3.0
      device: //192.168.x.y/share/subfolder
```

Though I've never tried that personally.

Hope this helps!
